name: Build Docker Image - CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/Mik3dev/uniswap-v2-arbitrage-bot

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    outputs:
      image_version: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      image_name: ${{ env.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: type=sha,prefix=-

      - name: Build and push
        id: image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log output
        run: |
          echo ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          echo ${{ steps.meta.outputs.json }}
